# NUMPY 

In [104]:
import numpy as np

In [105]:
my_array = np.array([[3,673,753,39]])

In [106]:
my_array

array([[  3, 673, 753,  39]])

In [107]:
my_array[0,3]
my_array.shape


(1, 4)

In [108]:
my_array[0,0]=56
my_array

array([[ 56, 673, 753,  39]])

## Array Creation : Conversion from other Python Structures

In [109]:
list_array = np.array([[1,2,3],[5,6,7],[8,9,2]])
list_array

array([[1, 2, 3],
       [5, 6, 7],
       [8, 9, 2]])

In [110]:
list_array.dtype

dtype('int32')

In [111]:
list_array.shape

(3, 3)

In [112]:
list_array.size

9

In [113]:
matrix = np.array([[42,625,83],[26,92,90],[72,92,92],[78,90,98]])
matrix

array([[ 42, 625,  83],
       [ 26,  92,  90],
       [ 72,  92,  92],
       [ 78,  90,  98]])

shape function gives the shape/order of any matrix

In [114]:
matrix.shape

(4, 3)

Zeros :- it gives an array of order(x,y) with all elements zero

In [115]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

arange gives a list of arrays of range(x)

In [116]:
range = np.arange(19)
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [117]:
x = np.array([[56,65,78],[65,54,76]])
y = np.array([[65,98,45],[76,12,65]])
x+y
x*y
x/y
x-y

array([[ -9, -33,  33],
       [-11,  42,  11]])

It gives a linearly spaced matrix ; (x,y,z),
1. x is the starting value.
2. y is the ending value.
3. z is the number of arrays.

In [118]:
lspace = np.linspace(1,4,5)
lspace


array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [119]:
emp = np.empty((4,6))
emp

array([[4.67296746e-307, 1.69121096e-306, 8.01106038e-307,
        6.23054293e-307, 1.11261162e-306, 8.90104239e-307],
       [1.24610383e-306, 1.69118108e-306, 8.06632139e-308,
        1.20160711e-306, 1.69119330e-306, 1.29062229e-306],
       [1.60217812e-306, 1.37961370e-306, 1.42417629e-306,
        1.37961913e-306, 1.42418172e-306, 2.04712906e-306],
       [7.56589622e-307, 1.11258277e-307, 8.90111708e-307,
        3.22643519e-307, 9.79103798e-307, 2.46155235e-312]])

It gives an empty matrix form a previously made matrix
something like that

In [120]:
emp_like = np.empty_like(lspace)
emp_like

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

It gives an identity matrix of order(x)

In [121]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [122]:
ide.shape

(5, 5)

In [123]:
array = np.arange(100)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [124]:
array.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [125]:
arr = array.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [126]:
arr.shape

(100,)

axis 0 is for rows and axis 1 is for column

In [127]:
x = ([[1,2,3],[7,9,3],[6,9,2]])
arr = np.array(x)
arr

array([[1, 2, 3],
       [7, 9, 3],
       [6, 9, 2]])

In [128]:
arr.sum(axis=0)

array([14, 20,  8])

In [129]:
arr.sum(axis=1)

array([ 6, 19, 17])

Transpose of a matrix  "arr.T"

In [130]:
arr.T

array([[1, 7, 6],
       [2, 9, 9],
       [3, 3, 2]])

In [131]:
arr.flat

In [132]:
for items in arr.flat:
    print(items)

1
2
3
7
9
3
6
9
2


to check no. of dimensions

In [133]:
arr.ndim

2

In [134]:
arr.size

9

In [135]:
arr.nbytes

36

* it there is no () then it is used as attrbute
* if there is () then it is used as fumction

In [136]:
one = np.array([1,3,2,73,97])
one.argmax()


4

In [137]:
one.argmin()

0

In [138]:
one.argsort()

array([0, 2, 1, 3, 4], dtype=int64)

In [143]:
ar = ([[7,8,2],[5,2,9],[1,0,4]])
ar = np.array(ar)
ar

array([[7, 8, 2],
       [5, 2, 9],
       [1, 0, 4]])

In [145]:
ar.argmin()

7

In [146]:
ar.argmax()

5

In [151]:
ar.argmin(axis=0)

array([2, 2, 0], dtype=int64)

In [152]:
ar.argmin(axis=1)

array([2, 1, 1], dtype=int64)

In [154]:
ar.argsort(axis=0)

array([[2, 2, 0],
       [1, 1, 2],
       [0, 0, 1]], dtype=int64)

In [156]:
ar.ravel()
ar.reshape(9,1)

array([[7],
       [8],
       [2],
       [5],
       [2],
       [9],
       [1],
       [0],
       [4]])

In [159]:
np.sqrt(ar)

array([[2.64575131, 2.82842712, 1.41421356],
       [2.23606798, 1.41421356, 3.        ],
       [1.        , 0.        , 2.        ]])

In [160]:
ar.sum()

38

In [161]:
ar.max()

9

In [162]:
ar

array([[7, 8, 2],
       [5, 2, 9],
       [1, 0, 4]])

In [164]:
ar.shape

(3, 3)

In [167]:
np.where(ar>7)

(array([0, 1], dtype=int64), array([1, 2], dtype=int64))

In [172]:
np.count_nonzero(ar)

8

In [176]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 2], dtype=int64))

In [177]:
y =([[52,52,91],[25,91,57],[78,32,91]])
y = np.array(y)
y

array([[52, 52, 91],
       [25, 91, 57],
       [78, 32, 91]])

In [178]:
#axis =1 is vertical and axis =-1 is horizontal
print("sum of all values:" , y.sum())
print("sum of each row:", y.sum(axis=1))
print("sum of each column:",y.sum(axis=0))
print("mean of all values:", y.mean())
print("mean of each row:",y.mean(axis=1))
print("mean of each column:", y.mean(axis=0))
print("---"*10)
print("standard deviation of all values", y.std())
print("standard deviation of each row:", y.std(axis=1))
print("standard deviation of each column:", y.std(axis=0))
print("--"*10)
print("min and mac of all values:", y.min(), y.max())
print("min amd max of each row:", y.min(axis=1), y.max(axis=1))
print("min and max of each column: ", y.min(axis=-1), y.max(axis=-1))

sum of all values: 569
sum of each row: [195 173 201]
sum of each column: [155 175 239]
mean of all values: 63.22222222222222
mean of each row: [65.         57.66666667 67.        ]
mean of each column: [51.66666667 58.33333333 79.66666667]
------------------------------
standard deviation of all values 24.174264450617624
standard deviation of each row: [18.38477631 26.94851058 25.31139401]
standard deviation of each column: [21.63844316 24.4994331  16.02775371]
--------------------
min and mac of all values: 25 91
min amd max of each row: [52 25 32] [91 91 91]
min and max of each column:  [52 25 32] [91 91 91]
